"""naming livestreams

Revision ID: a5e99ce94e6c
Revises: e7ecbe67690b
Create Date: 2020-01-27 16:11:45.041382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5e99ce94e6c'
down_revision = 'e7ecbe67690b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('livestream', sa.Column('name', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('livestream', 'name')
    # ### end Alembic commands ###
